// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGTWOA4etcfvFD_IjLNPbpAn1KrqFoINI',
    appId: '1:719589377411:web:ce90e31ad2e67271c7e2b6',
    messagingSenderId: '719589377411',
    projectId: 'service-app-e81d4',
    authDomain: 'service-app-e81d4.firebaseapp.com',
    storageBucket: 'service-app-e81d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQG62fr4r-yDDlXB4zjpawuNoucZTrFA',
    appId: '1:719589377411:android:165982c846cf0a93c7e2b6',
    messagingSenderId: '719589377411',
    projectId: 'service-app-e81d4',
    storageBucket: 'service-app-e81d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmlLb8g5avpOEVuANZk5Qn45GUEnqpB0',
    appId: '1:719589377411:ios:4811fb6e56526fe9c7e2b6',
    messagingSenderId: '719589377411',
    projectId: 'service-app-e81d4',
    storageBucket: 'service-app-e81d4.appspot.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnmlLb8g5avpOEVuANZk5Qn45GUEnqpB0',
    appId: '1:719589377411:ios:4811fb6e56526fe9c7e2b6',
    messagingSenderId: '719589377411',
    projectId: 'service-app-e81d4',
    storageBucket: 'service-app-e81d4.appspot.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGTWOA4etcfvFD_IjLNPbpAn1KrqFoINI',
    appId: '1:719589377411:web:08d9c48dba6a54cac7e2b6',
    messagingSenderId: '719589377411',
    projectId: 'service-app-e81d4',
    authDomain: 'service-app-e81d4.firebaseapp.com',
    storageBucket: 'service-app-e81d4.appspot.com',
  );

}